/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.atm;

import java.awt.Color;
import java.awt.Container;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author I R F A N
 */
public class Statistics extends javax.swing.JFrame {

    private Container c;
    
    Connection con = null;
    PreparedStatement pst1,pst2,pst3,pst4,pst5,pst6,pst01,pst02 = null;
    ResultSet rs1,rs2,rs3,rs4,rs5,rs6,rs01,rs02 = null;
    
    public Statistics() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal Account System - - Statistical Analysis Dialog");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Account Number:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(47, 69, 159, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("All Balance:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(48, 180, 158, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Average Balance:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(48, 282, 158, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Saving Account:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(426, 38, 146, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Checking Account:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(402, 69, 170, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Credit Account:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(432, 100, 140, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("All Deposit:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(470, 167, 102, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("All Credit:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(484, 198, 88, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Average Deposit:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(418, 269, 154, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Average Credit:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(432, 300, 140, 22);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(213, 70, 163, 23);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setText("0");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(213, 179, 163, 23);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.setText("0");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(213, 283, 163, 23);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField4.setText("0");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(577, 39, 145, 23);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField5.setText("0");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(577, 70, 145, 23);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField6.setText("0");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(577, 101, 145, 23);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField7.setText("0");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(577, 168, 145, 23);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField8.setText("0");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(577, 199, 145, 23);

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField9.setText("0");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(577, 270, 145, 23);

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField10.setText("0");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(577, 301, 145, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/atm/icon11.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(73, 346, 133, 41);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/atm/icon5.png"))); // NOI18N
        jButton2.setText("Statistics");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(312, 346, 149, 41);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/atm/icon1.png"))); // NOI18N
        jButton3.setText("Return");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(577, 346, 131, 41);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
                AllMenu frame = new AllMenu();
                AllMenu.jButton5.setEnabled(false);
                AllMenu.jButton6.setEnabled(false);
                AllMenu.jButton7.setEnabled(false);
                frame.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/AccountInfo", "root","");
            
            pst1 = con.prepareStatement("SELECT COUNT(*) FROM `accountinfo`");
            rs1 = pst1.executeQuery();
            if(rs1.next()){
                jTextField1.setText(rs1.getString("COUNT(*)"));
            }
            pst2 = con.prepareStatement("SELECT * ,SUM(Balance) FROM accountinfo");
            rs2 = pst2.executeQuery();
            if(rs2.next()){
                jTextField2.setText(rs2.getString("SUM(Balance)"));
                jTextField7.setText(rs2.getString("SUM(Balance)"));
                jTextField8.setText("0.00");
            }
            pst3 = con.prepareStatement("SELECT * ,AVG(Balance) FROM accountinfo");
            rs3 = pst3.executeQuery();
            if(rs3.next()){
                jTextField3.setText(rs3.getString("AVG(Balance)"));
                jTextField9.setText(rs3.getString("AVG(Balance)"));
                jTextField10.setText("0.00");
            }
            pst4 = con.prepareStatement("SELECT COUNT(AccountID) FROM `accountinfo` WHERE AccountType='Saving Account'");
            rs4= pst4.executeQuery();
            if(rs4.next()){
                jTextField4.setText(rs4.getString("COUNT(AccountID)"));
            }
            pst5 = con.prepareStatement("SELECT COUNT(AccountID) FROM `accountinfo` WHERE AccountType='Checking Account'");
            rs5 = pst5.executeQuery();
            if(rs5.next()){
                jTextField5.setText(rs5.getString("COUNT(AccountID)"));
            }
            pst6 = con.prepareStatement("SELECT COUNT(AccountID) FROM `accountinfo` WHERE AccountType='Credit Account'");
            rs6 = pst6.executeQuery();
            if(rs6.next()){
                jTextField6.setText(rs6.getString("COUNT(AccountID)"));
            }
            
        }catch(SQLException ex){
            
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/AccountInfo", "root","");
            pst01 = con.prepareStatement("UPDATE accountinfo SET Balance = (Balance+(Balance*.01))");
            pst01.executeUpdate();
            
            try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/AccountInfo", "root","");
            
            pst1 = con.prepareStatement("SELECT COUNT(*) FROM `accountinfo`");
            rs1 = pst1.executeQuery();
            if(rs1.next()){
                jTextField1.setText(rs1.getString("COUNT(*)"));
            }
            pst2 = con.prepareStatement("SELECT * ,SUM(Balance) FROM accountinfo");
            rs2 = pst2.executeQuery();
            if(rs2.next()){
                jTextField2.setText(rs2.getString("SUM(Balance)"));
                jTextField7.setText(rs2.getString("SUM(Balance)"));
                jTextField8.setText("0.00");
            }
            pst3 = con.prepareStatement("SELECT * ,AVG(Balance) FROM accountinfo");
            rs3 = pst3.executeQuery();
            if(rs3.next()){
                jTextField3.setText(rs3.getString("AVG(Balance)"));
                jTextField9.setText(rs3.getString("AVG(Balance)"));
                jTextField10.setText("0.00");
            }
            pst4 = con.prepareStatement("SELECT COUNT(AccountID) FROM `accountinfo` WHERE AccountType='Saving Account'");
            rs4= pst4.executeQuery();
            if(rs4.next()){
                jTextField4.setText(rs4.getString("COUNT(AccountID)"));
            }
            pst5 = con.prepareStatement("SELECT COUNT(AccountID) FROM `accountinfo` WHERE AccountType='Checking Account'");
            rs5 = pst5.executeQuery();
            if(rs5.next()){
                jTextField5.setText(rs5.getString("COUNT(AccountID)"));
            }
            pst6 = con.prepareStatement("SELECT COUNT(AccountID) FROM `accountinfo` WHERE AccountType='Credit Account'");
            rs6 = pst6.executeQuery();
            if(rs6.next()){
                jTextField6.setText(rs6.getString("COUNT(AccountID)"));
            }
            
        }catch(SQLException ex){
            
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Statistics().setVisible(true);
        });
    }

    private void setIcon() {
        c = this.getContentPane();
        c.setLayout(null);
        c.setBackground(Color.ORANGE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("i1.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
